name: automerge
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@a58470325a3437bd872dace642422916828208e0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "version-upgrade"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "DanySK"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "version-upgrade"
          UPDATE_METHOD: "rebase"
